//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISample.SampleReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webservicex.net/", ConfigurationName="SampleReference.FedACHSoap")]
    public interface FedACHSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAPISample.SampleReference.getACHByNameResponse getACHByName(WebAPISample.SampleReference.getACHByNameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByNameResponse> getACHByNameAsync(WebAPISample.SampleReference.getACHByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAPISample.SampleReference.getACHByLocationResponse getACHByLocation(WebAPISample.SampleReference.getACHByLocationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByLocationResponse> getACHByLocationAsync(WebAPISample.SampleReference.getACHByLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByZipCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAPISample.SampleReference.getACHByZipCodeResponse getACHByZipCode(WebAPISample.SampleReference.getACHByZipCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByZipCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByZipCodeResponse> getACHByZipCodeAsync(WebAPISample.SampleReference.getACHByZipCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByFRBNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAPISample.SampleReference.getACHByFRBNumberResponse getACHByFRBNumber(WebAPISample.SampleReference.getACHByFRBNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByFRBNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByFRBNumberResponse> getACHByFRBNumberAsync(WebAPISample.SampleReference.getACHByFRBNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByRoutingNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAPISample.SampleReference.getACHByRoutingNumberResponse getACHByRoutingNumber(WebAPISample.SampleReference.getACHByRoutingNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/getACHByRoutingNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByRoutingNumberResponse> getACHByRoutingNumberAsync(WebAPISample.SampleReference.getACHByRoutingNumberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public partial class FedACHList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FedACHData[] fedACHsField;
        
        private int totalRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FedACHData[] FedACHs {
            get {
                return this.fedACHsField;
            }
            set {
                this.fedACHsField = value;
                this.RaisePropertyChanged("FedACHs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
                this.RaisePropertyChanged("TotalRecords");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net/")]
    public partial class FedACHData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string routingNumberField;
        
        private string officeCodeField;
        
        private string servicingFRBNumberField;
        
        private string recordTypeCodeField;
        
        private string changeDateField;
        
        private string newRoutingNumberField;
        
        private string customerNameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string zipcodeField;
        
        private string zipcodeExtensionField;
        
        private string telephoneAreaCodeField;
        
        private string telephonePrefixNumberField;
        
        private string telephoneSuffixNumberField;
        
        private string institutionStatusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RoutingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
                this.RaisePropertyChanged("RoutingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OfficeCode {
            get {
                return this.officeCodeField;
            }
            set {
                this.officeCodeField = value;
                this.RaisePropertyChanged("OfficeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServicingFRBNumber {
            get {
                return this.servicingFRBNumberField;
            }
            set {
                this.servicingFRBNumberField = value;
                this.RaisePropertyChanged("ServicingFRBNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RecordTypeCode {
            get {
                return this.recordTypeCodeField;
            }
            set {
                this.recordTypeCodeField = value;
                this.RaisePropertyChanged("RecordTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ChangeDate {
            get {
                return this.changeDateField;
            }
            set {
                this.changeDateField = value;
                this.RaisePropertyChanged("ChangeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NewRoutingNumber {
            get {
                return this.newRoutingNumberField;
            }
            set {
                this.newRoutingNumberField = value;
                this.RaisePropertyChanged("NewRoutingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("Zipcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZipcodeExtension {
            get {
                return this.zipcodeExtensionField;
            }
            set {
                this.zipcodeExtensionField = value;
                this.RaisePropertyChanged("ZipcodeExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TelephoneAreaCode {
            get {
                return this.telephoneAreaCodeField;
            }
            set {
                this.telephoneAreaCodeField = value;
                this.RaisePropertyChanged("TelephoneAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TelephonePrefixNumber {
            get {
                return this.telephonePrefixNumberField;
            }
            set {
                this.telephonePrefixNumberField = value;
                this.RaisePropertyChanged("TelephonePrefixNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TelephoneSuffixNumber {
            get {
                return this.telephoneSuffixNumberField;
            }
            set {
                this.telephoneSuffixNumberField = value;
                this.RaisePropertyChanged("TelephoneSuffixNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string InstitutionStatusCode {
            get {
                return this.institutionStatusCodeField;
            }
            set {
                this.institutionStatusCodeField = value;
                this.RaisePropertyChanged("InstitutionStatusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByName", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public string Name;
        
        public getACHByNameRequest() {
        }
        
        public getACHByNameRequest(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByNameResponse", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public bool getACHByNameResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=1)]
        public WebAPISample.SampleReference.FedACHList FedACHLists;
        
        public getACHByNameResponse() {
        }
        
        public getACHByNameResponse(bool getACHByNameResult, WebAPISample.SampleReference.FedACHList FedACHLists) {
            this.getACHByNameResult = getACHByNameResult;
            this.FedACHLists = FedACHLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByLocation", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=1)]
        public string StateCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=2)]
        public string City;
        
        public getACHByLocationRequest() {
        }
        
        public getACHByLocationRequest(string Address, string StateCode, string City) {
            this.Address = Address;
            this.StateCode = StateCode;
            this.City = City;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByLocationResponse", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public bool getACHByLocationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=1)]
        public WebAPISample.SampleReference.FedACHList FedACHLists;
        
        public getACHByLocationResponse() {
        }
        
        public getACHByLocationResponse(bool getACHByLocationResult, WebAPISample.SampleReference.FedACHList FedACHLists) {
            this.getACHByLocationResult = getACHByLocationResult;
            this.FedACHLists = FedACHLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByZipCode", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByZipCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public string ZipCode;
        
        public getACHByZipCodeRequest() {
        }
        
        public getACHByZipCodeRequest(string ZipCode) {
            this.ZipCode = ZipCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByZipCodeResponse", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByZipCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public bool getACHByZipCodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=1)]
        public WebAPISample.SampleReference.FedACHList FedACHLists;
        
        public getACHByZipCodeResponse() {
        }
        
        public getACHByZipCodeResponse(bool getACHByZipCodeResult, WebAPISample.SampleReference.FedACHList FedACHLists) {
            this.getACHByZipCodeResult = getACHByZipCodeResult;
            this.FedACHLists = FedACHLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByFRBNumber", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByFRBNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public string FRBNumber;
        
        public getACHByFRBNumberRequest() {
        }
        
        public getACHByFRBNumberRequest(string FRBNumber) {
            this.FRBNumber = FRBNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByFRBNumberResponse", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByFRBNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public bool getACHByFRBNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=1)]
        public WebAPISample.SampleReference.FedACHList FedACHLists;
        
        public getACHByFRBNumberResponse() {
        }
        
        public getACHByFRBNumberResponse(bool getACHByFRBNumberResult, WebAPISample.SampleReference.FedACHList FedACHLists) {
            this.getACHByFRBNumberResult = getACHByFRBNumberResult;
            this.FedACHLists = FedACHLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByRoutingNumber", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByRoutingNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public string RoutingNumber;
        
        public getACHByRoutingNumberRequest() {
        }
        
        public getACHByRoutingNumberRequest(string RoutingNumber) {
            this.RoutingNumber = RoutingNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getACHByRoutingNumberResponse", WrapperNamespace="http://www.webservicex.net/", IsWrapped=true)]
    public partial class getACHByRoutingNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=0)]
        public bool getACHByRoutingNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net/", Order=1)]
        public WebAPISample.SampleReference.FedACHList FedACHLists;
        
        public getACHByRoutingNumberResponse() {
        }
        
        public getACHByRoutingNumberResponse(bool getACHByRoutingNumberResult, WebAPISample.SampleReference.FedACHList FedACHLists) {
            this.getACHByRoutingNumberResult = getACHByRoutingNumberResult;
            this.FedACHLists = FedACHLists;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FedACHSoapChannel : WebAPISample.SampleReference.FedACHSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FedACHSoapClient : System.ServiceModel.ClientBase<WebAPISample.SampleReference.FedACHSoap>, WebAPISample.SampleReference.FedACHSoap {
        
        public FedACHSoapClient() {
        }
        
        public FedACHSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FedACHSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FedACHSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FedACHSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAPISample.SampleReference.getACHByNameResponse WebAPISample.SampleReference.FedACHSoap.getACHByName(WebAPISample.SampleReference.getACHByNameRequest request) {
            return base.Channel.getACHByName(request);
        }
        
        public bool getACHByName(string Name, out WebAPISample.SampleReference.FedACHList FedACHLists) {
            WebAPISample.SampleReference.getACHByNameRequest inValue = new WebAPISample.SampleReference.getACHByNameRequest();
            inValue.Name = Name;
            WebAPISample.SampleReference.getACHByNameResponse retVal = ((WebAPISample.SampleReference.FedACHSoap)(this)).getACHByName(inValue);
            FedACHLists = retVal.FedACHLists;
            return retVal.getACHByNameResult;
        }
        
        public System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByNameResponse> getACHByNameAsync(WebAPISample.SampleReference.getACHByNameRequest request) {
            return base.Channel.getACHByNameAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAPISample.SampleReference.getACHByLocationResponse WebAPISample.SampleReference.FedACHSoap.getACHByLocation(WebAPISample.SampleReference.getACHByLocationRequest request) {
            return base.Channel.getACHByLocation(request);
        }
        
        public bool getACHByLocation(string Address, string StateCode, string City, out WebAPISample.SampleReference.FedACHList FedACHLists) {
            WebAPISample.SampleReference.getACHByLocationRequest inValue = new WebAPISample.SampleReference.getACHByLocationRequest();
            inValue.Address = Address;
            inValue.StateCode = StateCode;
            inValue.City = City;
            WebAPISample.SampleReference.getACHByLocationResponse retVal = ((WebAPISample.SampleReference.FedACHSoap)(this)).getACHByLocation(inValue);
            FedACHLists = retVal.FedACHLists;
            return retVal.getACHByLocationResult;
        }
        
        public System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByLocationResponse> getACHByLocationAsync(WebAPISample.SampleReference.getACHByLocationRequest request) {
            return base.Channel.getACHByLocationAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAPISample.SampleReference.getACHByZipCodeResponse WebAPISample.SampleReference.FedACHSoap.getACHByZipCode(WebAPISample.SampleReference.getACHByZipCodeRequest request) {
            return base.Channel.getACHByZipCode(request);
        }
        
        public bool getACHByZipCode(string ZipCode, out WebAPISample.SampleReference.FedACHList FedACHLists) {
            WebAPISample.SampleReference.getACHByZipCodeRequest inValue = new WebAPISample.SampleReference.getACHByZipCodeRequest();
            inValue.ZipCode = ZipCode;
            WebAPISample.SampleReference.getACHByZipCodeResponse retVal = ((WebAPISample.SampleReference.FedACHSoap)(this)).getACHByZipCode(inValue);
            FedACHLists = retVal.FedACHLists;
            return retVal.getACHByZipCodeResult;
        }
        
        public System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByZipCodeResponse> getACHByZipCodeAsync(WebAPISample.SampleReference.getACHByZipCodeRequest request) {
            return base.Channel.getACHByZipCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAPISample.SampleReference.getACHByFRBNumberResponse WebAPISample.SampleReference.FedACHSoap.getACHByFRBNumber(WebAPISample.SampleReference.getACHByFRBNumberRequest request) {
            return base.Channel.getACHByFRBNumber(request);
        }
        
        public bool getACHByFRBNumber(string FRBNumber, out WebAPISample.SampleReference.FedACHList FedACHLists) {
            WebAPISample.SampleReference.getACHByFRBNumberRequest inValue = new WebAPISample.SampleReference.getACHByFRBNumberRequest();
            inValue.FRBNumber = FRBNumber;
            WebAPISample.SampleReference.getACHByFRBNumberResponse retVal = ((WebAPISample.SampleReference.FedACHSoap)(this)).getACHByFRBNumber(inValue);
            FedACHLists = retVal.FedACHLists;
            return retVal.getACHByFRBNumberResult;
        }
        
        public System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByFRBNumberResponse> getACHByFRBNumberAsync(WebAPISample.SampleReference.getACHByFRBNumberRequest request) {
            return base.Channel.getACHByFRBNumberAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAPISample.SampleReference.getACHByRoutingNumberResponse WebAPISample.SampleReference.FedACHSoap.getACHByRoutingNumber(WebAPISample.SampleReference.getACHByRoutingNumberRequest request) {
            return base.Channel.getACHByRoutingNumber(request);
        }
        
        public bool getACHByRoutingNumber(string RoutingNumber, out WebAPISample.SampleReference.FedACHList FedACHLists) {
            WebAPISample.SampleReference.getACHByRoutingNumberRequest inValue = new WebAPISample.SampleReference.getACHByRoutingNumberRequest();
            inValue.RoutingNumber = RoutingNumber;
            WebAPISample.SampleReference.getACHByRoutingNumberResponse retVal = ((WebAPISample.SampleReference.FedACHSoap)(this)).getACHByRoutingNumber(inValue);
            FedACHLists = retVal.FedACHLists;
            return retVal.getACHByRoutingNumberResult;
        }
        
        public System.Threading.Tasks.Task<WebAPISample.SampleReference.getACHByRoutingNumberResponse> getACHByRoutingNumberAsync(WebAPISample.SampleReference.getACHByRoutingNumberRequest request) {
            return base.Channel.getACHByRoutingNumberAsync(request);
        }
    }
}
